version: '3'
services:
  client-management-ms:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=client
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
